Add a client instance to function handler params
slackapi/deno-slack-sdk pull request #101
Opened 2022-09-12 23:13 UTC by selfcontained

###  Summary

This extends the context argument passed into function handlers (main handler and interactivity handlers) to include a `client` property, which is a `SlackAPI()` instance on behalf of the `deno-slack-api` library.

Function handlers can make Slack API calls w/ the provided `client` property.
```ts
export default SlackFunction(MyFunction, async ({ inputs, client }) => {
    const resp = await client.chat.postMessage({
      channel: inputs.approval_channel_id,
      blocks: {
        //...
      },
    });

    if (!resp.ok) {
      console.log("Error posting message", resp);
    }

    return {
      completed: false,
    };
  },
)
```

Additional handlers, such as `blockActions`, `viewSubmission`, `viewClosed` and the `unhandledError` handler also receive a `client` instance.

### Details

* The client instance is created with the `token` that the [deno-slack-runtime](https://github.com/slackapi/deno-slack-runtime) provides all handlers.
* If `env["SLACK_API_URL"]` is set, the client will set the `slackApiUrl` configuration option with it.
* `deno-slack-api` becomes a dependency of this library, so we'll want to keep it current as we publish new versions of it.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/{project_slug}/blob/main/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2022-09-12 23:20 UTC, selfcontained commented on build_npm.ts
> +Deno.copyFileSync("README.md", "npm/README.md");
new version of deno has some `fmt` adjustments that this picked up.

2022-09-13 16:45 UTC, filmaj requested changes
Looks good but doesn't seem to work with the old `SlackFunctionHandler` approach.

Other than that, I think keeping the existing export name for the slackAPI as the main deno-slack-api module does (`SlackAPI`) makes sense.

One more note: it looks like with `enrichContext` we are inching towards a middleware-like pattern. Perhaps something to keep in mind in case we want to add further enrichment of different kinds down the road. Worth noting that all of the various languages that Bolt supports implement the middleware pattern. This only applies to the old platform, but, apps implementing OAuth (to either enable distribution on the Slack app store or to assume permissions on behalf of a user to do things like post messages as a user or update a user's status) would regularly implement a middleware layer that would look up installation information (like team id and interacting user id) to retrieve the right token to use for specific events (particularly necessary for apps that are installed to multiple unrelated Workspaces). This was such a common pattern that we implemented '[Installation Stores](https://slack.dev/bolt-js/concepts#authenticating-oauth)' in Bolt. While not needed for deno-slack-sdk apps, I think it's a salient use case to keep in mind moving forward. I could see devs wanting to, down the road, use a similar middleware-layer pattern to do things like retrieve user-specific contextual information from their own datastores to inject directly into handler contexts.

It wouldn't surprise me if 6-12 months down the road we refactor the approach implemented in this PR to more generally implement middleware.

2022-09-13 17:07 UTC, shapirone reviewed
Dropping some comments since I know we're revisiting the problem Fil mentioned above

2022-09-13 17:56 UTC, selfcontained commented on src/functions/enrich-context.ts
> +  const slackApiUrl = (context.env || {})["SLACK_API_URL"];
At runtime this is reliant on w/e `deno-slack-runtime` passes in to the top level handler. While it "should" be set, and is currently, this is a safety measure against something changing on accident in `deno-slack-runtime`.

2022-09-13 18:12 UTC, filmaj commented on src/functions/slack-function.ts
> +    //@ts-ignore - intentionally specifying the provided functionHandler as the `this` arg for the handler's call
LMAO that @ts-expect-error and @ts-ignore are actual GitHub users 😂

2022-09-13 18:43 UTC, filmaj approved these changes
Works with the ol' `SlackFunctionHandler`!

2022-09-13 18:43 UTC, filmaj commented on docs/functions-action-handlers.md
> +export default SlackFunction(ApprovalFunction, async ({ inputs, client }) => {
Oh man good call to update these docs - totally slipped my mind!

2022-09-13 20:04 UTC, selfcontained commented on src/functions/slack-function.ts
> +    //@ts-ignore - intentionally specifying the provided functionHandler as the `this` arg for the handler's call
Love the hover cards 😄

2022-09-13 21:21 UTC, merged