Added message_ts and message_context
slackapi/deno-slack-sdk pull request #113
Opened 2022-10-11 19:19 UTC by cchensh

###  Summary

Added `message_ts` to `SlackPrimitiveTypes` and `message_context` to `CustomSlackTypes`. 

Created new `MessageContextType` as the new Custom Type.

Requirements can be found below: 

- `message_ts` should be added to SlackPrimitiveTypes as a simple string
- `message_context` should be added to CustomSlackTypes as a Custom Type definition of an object with properties that can be found here:
https://corp.quip.com/9T6nAE8mUHxn/Reply-In-Thread-Builtin-Function#temp:C:VKKb19fca4ebf8c44c2b9b6732bc

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/{project_slug}/blob/main/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2022-10-11 19:44 UTC, cchensh commented on src/schema/slack/types/mod.ts
> +  message_ts: "string",
From the doc it looks like we should use `slack#/types/message_ts` type instead of plain string? @shapirone?

2022-10-11 19:46 UTC, shapirone requested changes
Sorry, forgot to mention one other spot — `FunctionInputRuntimeType` needs to know to treat `message_ts` as a `string` at runtime. You can add a check for `message_ts` at [this line](https://github.com/slackapi/deno-slack-sdk/blob/main/src/functions/types.ts#L91).

When these updates are made this will be looking pretty good and we just need to verify it works e2e in the client.

2022-10-11 19:46 UTC, shapirone commented on src/schema/slack/types/mod.ts
> +  message_ts: "string",
This needs to be `message_ts: "slack#/types/message_ts"`

2022-10-11 19:46 UTC, shapirone commented on src/schema/slack/types/custom/message_context.ts
> +  },
We should add `required: ["message_ts"]` here since that always must be provided. The others are optional

2023-02-02 21:22 UTC, filmaj commented
Hello after a few months @cchensh (cc @shapirone)!

So we just merged in the big SDK refactor we worked on. I rebased this branch on the latest main and pushed it up to your branch (hope you don't mind). Thanks to Neil, he gave me an idea on how to test this PR:

1. Pull in the latest `functions.list` API payload. That has a reply-in-thread built-in function definition which I used to generate the latest built-in functions available.
2. In the ensuing `git diff`, it looks like the SendMessage built-in now provides a message-context output parameter! 👀 
3. There's a new reply-in-thread built-in function that takes as input a message-context parameter.

So, I made a small change to the hello world / send a greeting sample so that the bottom of its workflow definition looks like this:

```
const msgStep = GreetingWorkflow.addStep(Schema.slack.functions.SendMessage, {
  channel_id: inputForm.outputs.fields.channel,
  message: greetingFunctionStep.outputs.greeting,
});

GreetingWorkflow.addStep(Schema.slack.functions.ReplyInThread, {
  message_context: msgStep.outputs.message_context,
  message: "hey look i can reply in thread using message_context now too woot",
});

export default GreetingWorkflow;
```

.. and that seems to work! So I think this PR is functionally OK 👍 

<img width="483" alt="Screenshot 2023-02-02 at 4 17 06 PM" src="https://user-images.githubusercontent.com/52645/216452328-6899ee6c-e591-4c4b-9763-cdb595d843ab.png">

I'm gonna look at adding a few more tests to this PR (in our fancy new `tests/integration` directory, to make sure the sub-properties on message-context are of the correct type and whatnot) and then I think it is good to merge.

2023-02-02 21:37 UTC, filmaj approved these changes

2023-02-02 21:37 UTC, merged