Update platform naming
slackapi/deno-slack-sdk pull request #164
Opened 2023-04-12 15:33 UTC by WilliamBergamin

###  Summary

This PR aims to update the project to follow the new Slack Term Glossary, this mainly affect documentation and comments, variable names were left unchanged to avoid breaking changes.

Some liberty was taken to reduce the number of proper nouns used in headers and titles (ex: Events -> events) but this was not applied everywhere, lmk if this PR should include a more extensive update of these terms

### Requirements 

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2023-04-12 19:56 UTC, jesselawson approved these changes
dab.jpeg

2023-04-12 23:32 UTC, shapirone requested changes
Mostly small comments, opened a discussion in Slack regarding using `*Fn` as a naming convention for function signature types (which would help us avoid the potentially dangerous name update)

2023-04-13 20:14 UTC, WilliamBergamin commented on src/functions/interactivity/view_router_test.ts
> +type SlackViewClosedHandlerTesterType = {
`Type` changed in favor of `Signature`

2023-04-13 20:14 UTC, WilliamBergamin commented on src/functions/interactivity/view_router_test.ts
> +type SlackViewSubmissionHandlerTesterType = {
`Type` changed in favor of `Signature`

2023-04-13 20:14 UTC, WilliamBergamin commented on src/functions/interactivity/block_suggestion_router_test.ts
> +type SlackSuggestionHandlerTesterType = {
`Type` changed in favor of `Signature`

2023-04-13 20:14 UTC, WilliamBergamin commented on src/functions/interactivity/block_actions_router_test.ts
> +type SlackActionHandlerTesterType = {
`Type` changed in favor of `Signature`

2023-04-13 23:18 UTC, shapirone approved these changes
🚢

2023-04-13 23:19 UTC, merged