adding manifest property for  token url configs
slackapi/deno-slack-sdk pull request #198
Opened 2023-08-16 01:32 UTC by uhunnyslack

###  Summary

Describe the goal of this PR. Mention any related Issue numbers.

### Requirements (place an `x` in each `[ ]`)

* [ ] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2023-08-16 14:35 UTC, WilliamBergamin commented
@uhunnyslack I was working on #194 that aims to consolidate the provider args options `type` and the `type` found in the `manifest` we decided to put this PR on hold waiting to see if your changes could conflict with mine

Do you know if there will be a new provider other changes coming in the near future and would it be worth it to create a typescript type dedicated to PKCE providers?

2023-08-17 14:46 UTC, filmaj requested changes
Overall LGTM, left some comments on removing the apps.json file and adding more docs.

Let's coordinate in Slack re: releasing this.

2023-08-17 14:46 UTC, filmaj commented on src/providers/oauth2/types.ts
> +  "use_basic_authentication_scheme"?: boolean;
Let's add a JSdoc here to explain what this is used for.

2023-08-17 14:46 UTC, filmaj commented on .slack/apps.json
> +{}
Please remove this file.

2023-09-15 17:08 UTC, closed without merging