Add Share Canvas in thread to the deno sdk
slackapi/deno-slack-sdk pull request #311
Opened 2024-05-02 14:31 UTC by rafaelamsili

### Summary

This PR add the new released Share Canvas in thread to the deno sdk and update labels for the owner in copy canvas, create canvas and create channel canvas

| Field  | Type | Description | Required
| -------- | ------- | ------- | ------- |
| canvas_id  | slack#/types/canvas_id | The id of the canvas that will be shared    | true |
| message_context |  slack#/types/message_context | The reference to the root message that the canvas will be shared as a reply    |  true |
| access_level | string | The access level that the canvas will be shared. It can be `view` or `edit`   |  false - defaults to `view` |
| message    | slack#/types/rich_text | Optional rich text message that will be send when sharing the canvas  |  false |
| reply_broadcast    | boolean | If selected will also broadcast the message to the channel |  false - defaults to `false` |

### Testing

Create an app using the functions and see that it perform the actions

### Requirements 
- Canvas need to be enabled in the org

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've ran `deno task test` after making the changes.

2024-05-02 14:31 UTC, rafaelamsili commented on src/schema/slack/functions/canvas_copy.ts
> +        description: "Person",
This label changed in the built in

2024-05-03 16:52 UTC, filmaj commented
@rafaelamsili did you run the generation script for this (it seems to me like no)? Because the `mod.ts` is missing the import of the new function, so there's no way for a developer to actually use this as-is.

2024-05-03 17:12 UTC, filmaj requested changes
The one thing we're missing is importing the new function in this file and exposing it as part of the export: https://github.com/slackapi/deno-slack-sdk/blob/main/src/schema/slack/functions/mod.ts

2024-05-03 17:30 UTC, filmaj approved these changes

2024-05-03 17:31 UTC, merged

2024-05-03 17:31 UTC, rafaelamsili commented
> @rafaelamsili did you run the generation script for this (it seems to me like no)? Because the `mod.ts` is missing the import of the new function, so there's no way for a developer to actually use this as-is.

Good catch 🦅 👁️  about the mod change. I ran the generation script but there was a lot of noise from other functions so I just committed those changes.